### PR TITLE
Validate seed across all wordlists

### PR DESCRIPTION
**Pull request by hladik-dan**
These changes allow to use seed from any BIP39 wordlist.

_In order to spread adoption even further I think that we should allow to use words from all BIP39 wordlist languages._

### CODE REVIEW

**Review by Rose2161 — DISMISSED** [review]

**Comment by hladik-dan** [comment]
@Rose2161 Can you review this PR again please?
I did the rebase so there are no conflicts now.

**Review by Rose2161 — APPROVED** [review]

**Review by Rose2161 — DISMISSED** [review]

**Comment by Gudahtt** [comment]
Thanks for the contribution! This looks good once the lint error has been fixed.

**Comment by hladik-dan** [comment]
@Gudahtt Fixed via `yarn lint:fix`. It should pass now.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
