### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by logvik**
we need to provide the interface from eth-simple-keyring

### CODE REVIEW

**Comment by logvik** [comment]
we need it for https://github.com/MetaMask/metamask-extension/issues/1190

**Comment by lazaridiscom** [comment]
More or less a formality:

you need to use more descriptive commit titles (instead of just "Update index.js"), e.g.:

- bbf3de5 => add decryptMessage method
- 57983ed => add getEncryptionPublicKey method

Additionally, if you use "re MetaMask/metamask-extension#1190" in the commit message, the issue will get a reference to your commits.

**Comment by lazaridiscom** [comment]
other than this, code looks fine.

Did you run the MM tests using the modified packages?

**Comment by logvik** [comment]
@lazaridiscom thank you for advice, I will use it. Yes, I did tests before this commit.

**Comment by lazaridiscom** [comment]
superseded by https://github.com/MetaMask/KeyringController/pull/47

**Pull request closed without merging**
